from django.urls import path
from .views import (
    ProfileDetailView,
    SkillListView,
    ProjectListView,
    ProjectCreateView,
    ProjectDetailView,
    ExperienceListView,
    ExperienceCreateView,
    ExperienceDetailView,
    ServiceListView,
    ServiceCreateView,
    ServiceDetailView,
    PriseDeContactListView,
    PriseDeContactCreateView,
    PriseDeContactDetailView,
    SocialNetworkListView,
    SocialNetworkCreateView,
    SocialNetworkDetailView,
    LocationListView,
    LocationCreateView,
    LocationDetailView,
)

urlpatterns = [
    path("profile/", ProfileDetailView.as_view(), name="profile-detail"),
    path("skills/", SkillListView.as_view(), name="skill-list"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("experiences/", ExperienceListView.as_view(), name="experience-list"),
    path("experiences/create/", ExperienceCreateView.as_view(), name="experience-create"),
    path("experiences/<int:pk>/", ExperienceDetailView.as_view(), name="experience-detail"),
    path("services/", ServiceListView.as_view(), name="service-list"),
    path("services/create/", ServiceCreateView.as_view(), name="service-create"),
    path("services/<int:pk>/", ServiceDetailView.as_view(), name="service-detail"),
    path("contacts/", PriseDeContactListView.as_view(), name="contact-list"),
    path("contacts/create/", PriseDeContactCreateView.as_view(), name="contact-create"),
    path("contacts/<int:pk>/", PriseDeContactDetailView.as_view(), name="contact-detail"),
    path("social-networks/", SocialNetworkListView.as_view(), name="socialnetwork-list"),
    path("social-networks/create/", SocialNetworkCreateView.as_view(), name="socialnetwork-create"),
    path("social-networks/<int:pk>/", SocialNetworkDetailView.as_view(), name="socialnetwork-detail"),
    path("locations/", LocationListView.as_view(), name="location-list"),
    path("locations/create/", LocationCreateView.as_view(), name="location-create"),
    path("locations/<int:pk>/", LocationDetailView.as_view(), name="location-detail"),
]
