# Generated by Django 6.0.1 on 2026-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(default=50, verbose_name='Proficiency (%)'),
        ),
    ]
